/*
 * Main.java
 *
 * Created on 9 de junio de 2010, 16:30
 */


import javax.swing.*;
import java.io.*;
import java.util.Date;


/**
 *
 * @author  ceina
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {
        initComponents();
        FormCrear.setVisible(true);
        FormFitxaPeli.setVisible(true);
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        FormFitxaPeli = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        titol = new javax.swing.JTextField();
        anypeli = new javax.swing.JTextField();
        directorpeli = new javax.swing.JTextField();
        generepeli = new javax.swing.JTextField();
        preucost = new javax.swing.JTextField();
        plloguer = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        FormCrear = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nregistre = new javax.swing.JTextField();
        idpeli = new javax.swing.JTextField();
        nompeli = new javax.swing.JTextField();
        inilloguer = new javax.swing.JTextField();
        preulloguer = new javax.swing.JTextField();
        botoPrimera = new javax.swing.JButton();
        botoSeguent = new javax.swing.JButton();
        botoAnterior = new javax.swing.JButton();
        botoUltima = new javax.swing.JButton();
        llistatBD = new javax.swing.JInternalFrame();
        list1 = new java.awt.List();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        newentryMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        listBDMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestió de Videoclub");

        desktopPane.setToolTipText("ObrirFitxa");
        desktopPane.setEnabled(false);
        desktopPane.setPreferredSize(new java.awt.Dimension(600, 800));

        FormFitxaPeli.setClosable(true);
        FormFitxaPeli.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        FormFitxaPeli.setTitle("Fitxa Peli");
        FormFitxaPeli.setVisible(true);

        jLabel7.setText("Id:");

        jLabel8.setText("Titol:");

        jLabel9.setText("Any:");

        jLabel10.setText("Director:");

        jLabel11.setText("Genere:");

        jLabel12.setText("Preu cost:");

        jLabel13.setText("Preu lloguer:");

        jLabel14.setText("Total amortitzat:");

        id.setEditable(false);
        id.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        titol.setEditable(false);
        titol.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        anypeli.setEditable(false);
        anypeli.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        directorpeli.setEditable(false);
        directorpeli.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        generepeli.setEditable(false);
        generepeli.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        preucost.setEditable(false);
        preucost.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        plloguer.setEditable(false);
        plloguer.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        total.setEditable(false);
        total.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        javax.swing.GroupLayout FormFitxaPeliLayout = new javax.swing.GroupLayout(FormFitxaPeli.getContentPane());
        FormFitxaPeli.getContentPane().setLayout(FormFitxaPeliLayout);
        FormFitxaPeliLayout.setHorizontalGroup(
            FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormFitxaPeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(directorpeli, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(titol, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(anypeli, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(plloguer, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(generepeli, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(preucost, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap())
        );
        FormFitxaPeliLayout.setVerticalGroup(
            FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormFitxaPeliLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(titol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anypeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directorpeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(generepeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(preucost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(plloguer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormFitxaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        FormFitxaPeli.setBounds(380, 20, 330, 300);
        desktopPane.add(FormFitxaPeli, javax.swing.JLayeredPane.DEFAULT_LAYER);

        FormCrear.setClosable(true);
        FormCrear.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        FormCrear.setTitle("Fitxa Lloguer");
        FormCrear.setMinimumSize(new java.awt.Dimension(450, 300));
        FormCrear.setPreferredSize(new java.awt.Dimension(450, 300));
        FormCrear.setRequestFocusEnabled(false);
        FormCrear.setVisible(true);

        jLabel1.setText("Nombre de Registre:");

        jLabel2.setText("Nom de la pel·lícula:");

        jLabel3.setText("Data inici de lloguer:");

        jLabel5.setText("Preu Lloguer:");

        jLabel6.setText("Id de la pel·lícula:");

        nregistre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        idpeli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        idpeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpeliActionPerformed(evt);
            }
        });

        nompeli.setEditable(false);

        inilloguer.setEditable(false);

        preulloguer.setEditable(false);
        preulloguer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        preulloguer.setText("0");

        botoPrimera.setText("Primera");

        botoSeguent.setText("Seguent");

        botoAnterior.setText("Anterior");

        botoUltima.setText("Ultima");

        javax.swing.GroupLayout FormCrearLayout = new javax.swing.GroupLayout(FormCrear.getContentPane());
        FormCrear.getContentPane().setLayout(FormCrearLayout);
        FormCrearLayout.setHorizontalGroup(
            FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormCrearLayout.createSequentialGroup()
                        .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FormCrearLayout.createSequentialGroup()
                                        .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(FormCrearLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(23, 23, 23)))
                                .addGroup(FormCrearLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(21, 21, 21)))
                            .addGroup(FormCrearLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(54, 54, 54)))
                        .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preulloguer, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(inilloguer, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(nompeli, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(nregistre, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(idpeli, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(88, 88, 88))
                    .addGroup(FormCrearLayout.createSequentialGroup()
                        .addComponent(botoPrimera)
                        .addGap(18, 18, 18)
                        .addComponent(botoAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botoSeguent)
                        .addGap(18, 18, 18)
                        .addComponent(botoUltima)
                        .addContainerGap(84, Short.MAX_VALUE))))
        );
        FormCrearLayout.setVerticalGroup(
            FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormCrearLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nregistre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idpeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nompeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inilloguer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(preulloguer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(FormCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoPrimera)
                    .addComponent(botoAnterior)
                    .addComponent(botoSeguent)
                    .addComponent(botoUltima))
                .addGap(572, 572, 572))
        );

        FormCrear.setBounds(10, 20, 430, 300);
        desktopPane.add(FormCrear, javax.swing.JLayeredPane.DEFAULT_LAYER);

        llistatBD.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        llistatBD.setIconifiable(true);
        llistatBD.setMaximizable(true);
        llistatBD.setTitle("Llistat de Pelicules");

        list1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                list1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout llistatBDLayout = new javax.swing.GroupLayout(llistatBD.getContentPane());
        llistatBD.getContentPane().setLayout(llistatBDLayout);
        llistatBDLayout.setHorizontalGroup(
            llistatBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llistatBDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        llistatBDLayout.setVerticalGroup(
            llistatBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llistatBDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        llistatBD.setBounds(20, 20, 400, 300);
        desktopPane.add(llistatBD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fileMenu.setMnemonic('A');
        fileMenu.setText("Arxiu");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setMnemonic('C');
        newMenuItem.setText("Crear");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setMnemonic('O');
        openMenuItem.setText("Obrir");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        saveAsMenuItem.setMnemonic('G');
        saveAsMenuItem.setText("Guardar");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('S');
        exitMenuItem.setText("Sortir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Opcions");

        newentryMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        newentryMenuItem.setMnemonic('E');
        newentryMenuItem.setText("Entrar noves pel·licules");
        newentryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newentryMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(newentryMenuItem);

        copyMenuItem.setText("Lloguer de pel·licules");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Esborrar pel·licules amortitzades");
        editMenu.add(pasteMenuItem);

        listBDMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        listBDMenuItem.setMnemonic('L');
        listBDMenuItem.setText("Llistat total de la BD");
        listBDMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBDMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(listBDMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Consulta de pel·licules per títol");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Consulta de pel·licules per número");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem2);

        menuBar.add(editMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setMnemonic('A');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-747)/2, (screenSize.height-434)/2, 747, 434);
    }// </editor-fold>//GEN-END:initComponents
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        FormCrear.setVisible(true);
        Date avui = new Date();
        nregistre.setText("");
        idpeli.setText("");
        inilloguer.setText(avui.toString());
        preulloguer.setText("");
        nompeli.setText("");
        
}//GEN-LAST:event_newMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
       FormCrear.setVisible(true);
        try {
           RandomAccessFile file = new RandomAccessFile("Lloguer.txt","r");
           file.seek(0);
           nregistre.setText(file.readUTF());
           idpeli.setText(file.readUTF());
           inilloguer.setText(file.readUTF());
           preulloguer.setText(file.readUTF());
           nompeli.setText(file.readUTF());
           file.close();
       } catch (IOException e) {
           e.printStackTrace();
       }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        try {
           RandomAccessFile file = new RandomAccessFile("Lloguer.txt","rw");
           file.seek(file.length());
           file.writeUTF(nregistre.getText());
           file.writeUTF(idpeli.getText());
           file.writeUTF(nompeli.getText());
           file.writeUTF(inilloguer.getText());
           file.writeUTF(preulloguer.getText());
           file.close();
       } catch (IOException e) {
           JOptionPane.showMessageDialog(this,"No s'ha guardat bé!","Error",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void newentryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newentryMenuItemActionPerformed
        FormEntrar entrar = new FormEntrar(this,true);
        entrar.show();
    }//GEN-LAST:event_newentryMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
       FormAbove above = new FormAbove(this,true);
       above.setVisible(true);
       
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void listBDMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBDMenuItemActionPerformed
        llistatBD.setVisible(true);
        long cnt = 0;
        try {
            RandomAccessFile fsortida = new RandomAccessFile("Pelis.txt", "r");
            fsortida.seek(0);
            while (cnt != fsortida.length()) {
                System.out.println(fsortida.readUTF());
                list1.add(fsortida.readUTF());
                System.out.println(fsortida.readUTF());
                System.out.println(fsortida.readUTF());
                System.out.println(fsortida.readUTF());
                System.out.println(fsortida.readUTF());
                System.out.println(fsortida.readUTF());
                System.out.println(fsortida.readUTF());
                System.out.println("final");
                cnt = fsortida.getFilePointer();
            }
            fsortida.close();  
        } catch (IOException error) {
            error.printStackTrace();
        }
        
}//GEN-LAST:event_listBDMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       FormBuscar busca = new FormBuscar(this,true,true);
       busca.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormBuscar busca = new FormBuscar(this,true,false);
       busca.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void list1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_list1ItemStateChanged
       String s = list1.getSelectedItem();
       boolean trobat = false;
       try {
           RandomAccessFile file = new RandomAccessFile("Pelis.txt","r");
           file.seek(0);
           while (!trobat) {
               String idp = file.readUTF();
               String nom = file.readUTF();
               String any = file.readUTF();
               String dir = file.readUTF();
               String gen = file.readUTF();
               String cost = file.readUTF();
               String lloguer = file.readUTF();
               String totala = file.readUTF();
               if (s.compareTo(nom) == 0) {
                   trobat = true;
                   id.setText(idp);
                   titol.setText(nom);
                   anypeli.setText(any);
                   directorpeli.setText(dir);
                   generepeli.setText(gen);
                   preucost.setText(cost);
                   plloguer.setText(lloguer);
                   total.setText(totala);
               }
           }
           file.close();
           llistatBD.setVisible(false);
       } catch (IOException e) {
           e.printStackTrace();
       }
    }//GEN-LAST:event_list1ItemStateChanged

    private void idpeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpeliActionPerformed
        try {
           RandomAccessFile file = new RandomAccessFile("Pelis.txt","r");
           file.seek(0);
           boolean trobat = false;
           String n = idpeli.getText();
           while (!trobat) {
               String x = file.readUTF();
               String t = file.readUTF();
               file.readUTF();
               file.readUTF();
               file.readUTF();
               file.readUTF();
               String p = file.readUTF();
               file.readUTF();
               if (n.equals(x)) {
                   trobat = true;
                   nompeli.setText(t);
                   preulloguer.setText(p);
               }
           }
           file.close();
       } catch (Exception e) {
            e.printStackTrace();
       }
    }//GEN-LAST:event_idpeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame FormCrear;
    private javax.swing.JInternalFrame FormFitxaPeli;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField anypeli;
    private javax.swing.JButton botoAnterior;
    private javax.swing.JButton botoPrimera;
    private javax.swing.JButton botoSeguent;
    private javax.swing.JButton botoUltima;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JTextField directorpeli;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField generepeli;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idpeli;
    private javax.swing.JTextField inilloguer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private java.awt.List list1;
    private javax.swing.JMenuItem listBDMenuItem;
    private javax.swing.JInternalFrame llistatBD;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem newentryMenuItem;
    private javax.swing.JTextField nompeli;
    private javax.swing.JTextField nregistre;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JTextField plloguer;
    private javax.swing.JTextField preucost;
    private javax.swing.JTextField preulloguer;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JTextField titol;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
    
}
